### ISSUE TITLE
Merge FROM_EMAIL and MAILER_USERNAME?

### ISSUE THREAD

**Issue by forevermatt** [silinternational/email-service#1]
If I remember correctly, it's considered spammy to use a different `From` email address than the email address of the account you're and sending from, so it may be worth getting rid of the `FROM_EMAIL` variable and just using the `MAILER_USERNAME` value for that.

**EDIT:** Does the use of delegated accounts come in to play here?

**Comment by devon-sil** [comment]
This appears like they can serve different purposes, should we close this?

**Comment by briskt** [comment]
> This appears like they can serve different purposes, should we close this?

I think I agree with that. The two values can be different depending on your actual configuration.

**Comment by devon-sil** [comment]
Closing.
